version: '3.1'

services:

  database:
    container_name: database
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  nodejs:
    container_name: nodejs
    build: ./
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - database
